/* eslint-disable @next/next/no-head-element */

import '../styles/globals.css'
import Footer from './Footer'
import Navbar from './Navbar'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >

      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
